| [⬅️ Previous Session](practice_2-2_structured_data.ipynb) | [🏠 Course Home](../index.ipynb) | [➡️ Next Session](practice_4-1_pandas.ipynb) |

# Practice 3-1: Introduction to NumPy


<div class="run">
    ▶️ <b> Run the cell below. </b>
</div>


In [2]:
# Imports
import numpy as np


## 📚  **Practice 1.**  
Create the following arrays and assign the corresponding variable names:

1. `a`  
    $$
    \begin{bmatrix}
        4 & 5 & 0 & 12 & -1 \\
        8 & -21 & -4 & 6 & 3 \\
        17 & 1 & -13 & 7 & 0
    \end{bmatrix}
    $$

2. `b`  
    $$
    \begin{bmatrix}
        1.0 & 2.7 & 0 & 0.188 & 4.07 & 0.24
    \end{bmatrix}
    $$

3. `c`  
    $$
    \begin{bmatrix}
        0.4 \\
        0.8 \\
        1.2 \\
        1.6 \\
        2.0 \\
        2.4
    \end{bmatrix}
    $$


In [3]:
# Create 3x5 array of integers
a = np.array([[4, 5, 0, 12, -1], [8, -21, -4, 6, 3], [17, 1, -13, 7, 0]])

# Create a 1x6 array of floats
b = np.array([[1.0, 2.7, 0, 0.188, 4.07, 0.24]])

# Create a one-d array with 6 elements
c = np.array([0.4, 0.8, 1.2, 1.6, 2.0, 2.4])

## 📚  <b> Practice 2. </b> 
<ol class="alpha">
<li> Create a new array <code>d</code> of integers the multiples of 3 between 0 and 100.</li>
<li> Create an array <code>f</code> 10 evenly spaced elements between 0 and 2.</li> 
<li> Re-create array <code>c</code> from Practice 1c using a function. Assign this to variable name <code>g</code>. </li>
</ol>    

In [4]:
# a.
d = np.arange(1,100,3)
# b. 
f = np.linspace(0,2,10)
# c.
g = np.linspace(0.4,2.4,6)

## 📚  <b> Practice 3. </b> Assign the following to variables:
<ol class="alpha">
    <li> A 5x3 array of ones. </li>
    <li> A one-dimensional array of 6 zeros. </li> 
    <li> A 7x7 identity array. </li>
    <li> A random 10x10 array. </li>
</ol>

In [5]:
# a. 
ones = np.ones((5,3))
# b.
zeros6 = np.zeros(6)
# c.
eye = np.eye(7)
# d.
rand100 = np.random.rand(10,10)

## 📚  <b> Practice 4. </b> 
Use array methods and the array you created in Practice 2a (<code>d</code>) to count the number of multiples of 3 between 0 and 100.


In [6]:
# Print size of d
d.size

33


## 📚  <b> Practice 5. </b> Using the array you created in Practice 3d,
<ol class="alpha">
    <li> Print all the elements in column 4. </li>
    <li> Print all the elements in row 7. </li>
    <li> Extract the 4x4 subarray at the center of the array and assign it as a new variable. </li>
    <li> Print the last two values in column 10. </li>
</ol>

In [7]:
# a. Print all the elements in column 4
print(rand100[:,3])

# b. Print all the elements in row 7
print(rand100[6])

# c. Extract the 4x4 subarray at the center of the array and assign it as a new variable.
print(rand100[3:7,3:7])

# d. Print the last two values in column 10.
print(rand100[-2:,9])

[0.47355526 0.16640376 0.48631518 0.42032605 0.12026176 0.35326962
 0.70223167 0.45058564 0.921611   0.26428948]
[0.12746749 0.86608784 0.35305607 0.70223167 0.85187631 0.7585961
 0.21004781 0.54591833 0.06646384 0.74774   ]
[[0.42032605 0.37801466 0.83169814 0.26346432]
 [0.12026176 0.22708852 0.72144037 0.0987514 ]
 [0.35326962 0.10750686 0.88008533 0.43263521]
 [0.70223167 0.85187631 0.7585961  0.21004781]]
[0.70838202 0.41093916]


## 📚  <b> Practice 6. </b> 
Create a blank 8x8 matrix and fill it with a checkerboard pattern of 0s and 1s using indexing.


In [8]:
# Blank 8x8 array
q = np.zeros((8,8))

# Fill with checkerboard pattern
q[::2,1::2] = 1
q[1::2,::2] = 1
q

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

## 📚  <b> Practice 7. </b>
<ol class="alpha">
    <li> Create a 3x3 matrix with values ranging from 0 to 8. </li>
    <li> Reverse the order of elements in your random 10x10 array from 3d. </li>
</ol>

In [ ]:
# a. Create a 3x3 matrix with values ranging from 0 to 8
w = np.arange(0,9)
v = w.reshape(3,3)

# b. Reverse the order of elements in your random 10x10 array from 3d.
rand100_rev = np.flip(rand100)


## 📚  <b> Practice 8. </b> 
Create two random 1-D arrays of length 10. Merge them into a 2x10 array and then a 10x2 array.


In [10]:
# 2 random 1-D arrays
j = np.random.rand(10)
k = np.random.rand(10)

# Concat as 2x10 array
vert = np.vstack((j,k))
# Concat as 10x2 array
horiz = vert.T # or np.column_stack((j,k)).shape


## 📚  <b> Practice 9. </b>
<ol class="alpha">
    <li> Split your random 10x10 array from 3d into two 10x5 arrays. </li>
    <li> Combine the first 10x5 array from (a), the 10x2 array from 8b, and the other 10x5 array from (a). In other words, recombine the 10x10 array from 3d with two new columns in index positions 5 and 6. Your final array should have 10 rows and 12 columns. Verify this by printing the shape of the resulting array. </li>
</ol>


In [11]:
# Split into equal 10x5 arrays.
x,y = np.hsplit(rand100,[5])

# Concatenate x, y, and horiz
rand120 = np.concatenate((x,y,horiz), axis=1)

# Print dimensions
print(rand120.shape)

(10, 12)



## 📚  <b> Practice 10. </b>
<ol class="alpha">
    <li> Raise array <code>b</code> to the power of array <code>c</code>. </li>
    <li> Create a new 5x10 array of random values. Subtract the mean of each row from every value. </li>
</ol>


In [12]:
# a. 
b ** c

# b. 
# Random 5x10 array
rand50 = np.random.rand(5, 10)

# Calculate mean of each row
m = np.array([rand50.mean(axis=1)])
# Subtract mean from each element
l = rand50 - m.T
print(l)

[[-0.41170877  0.15229157  0.34946892  0.2381375  -0.0113315   0.13161321
  -0.1760515  -0.36044148 -0.12893971  0.21696174]
 [ 0.40968579  0.15228368  0.20724049 -0.33369976 -0.02910147 -0.4137152
   0.06196756  0.17497702 -0.33630459  0.10666647]
 [-0.37876503  0.19540316  0.41508675 -0.39110682  0.25720744  0.11413381
  -0.26093547 -0.22328425 -0.10556412  0.37782455]
 [ 0.21099536 -0.14109065  0.19566946  0.11854273 -0.44249867 -0.1864767
   0.04331053 -0.16904161  0.06026488  0.31032467]
 [ 0.38219275  0.1848438   0.00265078  0.33216692 -0.39019945  0.02188796
   0.01753881 -0.28219403 -0.24254002 -0.02634752]]


<hr style="border-top: 1px solid gray; margin-top: 24px; margin-bottom: 1px"></hr>